import type { Collection } from "tinacms";
import { ctaLinkFields, imageFieldUi, singletonUi } from "../shared/helpers";

export const servicesPageCollection: Collection = {
  name: "servicesPage",
  label: "Servicios · Cabecera y modalidades",
  path: "src/content/servicesPage",
  format: "json",
  ui: {
    ...singletonUi,
    router: () => "/servicios",
  },
  fields: [
    {
      type: "object",
      name: "hero",
      label: "1. Cabecera de la página",
      fields: [
        {
          type: "string",
          name: "label",
          label: "Etiqueta superior (badge)",
          description: "Texto pequeño sobre el título. Ej: «Servicios y Especialidades».",
          required: true,
        },
        {
          type: "string",
          name: "title",
          label: "Título principal (H1)",
          description: "Título grande de la página. Ej: «Acompañamiento psicológico para tu momento vital».",
          required: true,
        },
        {
          type: "string",
          name: "description",
          label: "Descripción introductoria",
          description: "Párrafo explicativo bajo el título principal.",
          required: true,
          ui: { component: "textarea" },
        },
      ],
    },
    {
      type: "object",
      name: "modalitiesSection",
      label: "2. Modalidades de atención (Presencial y Online)",
      fields: [
        {
          type: "string",
          name: "label",
          label: "Etiqueta de la sección",
          description: "Ej: «Modalidades de atención».",
          required: true,
        },
        {
          type: "string",
          name: "title",
          label: "Título de la sección (H2)",
          description: "Ej: «¿Cómo prefieres realizar tus sesiones?».",
          required: true,
        },
        {
          type: "object",
          name: "items",
          label: "Tarjetas de modalidad",
          list: true,
          ui: {
            itemProps: (item) => ({
              label: item?.title || "Nueva modalidad de atención",
            }),
          },
          fields: [
            {
              type: "string",
              name: "title",
              label: "Título de la modalidad",
              description: "Ej: «Consulta presencial en Málaga» o «Terapia online por videollamada».",
              required: true,
            },
            {
              type: "string",
              name: "badge",
              label: "Etiqueta destacada (opcional)",
              description: "Texto destacado arriba a la derecha. Ej: «Recomendada» (dejar vacío si no aplica).",
            },
            {
              type: "string",
              name: "icon",
              label: "Icono principal",
              description: "Identificador de Lucide (ej: lucide:map-pin, lucide:monitor, lucide:video).",
              required: true,
            },
            {
              type: "string",
              name: "description",
              label: "Descripción",
              description: "Texto explicativo detallando las ventajas o características de la modalidad.",
              required: true,
              ui: { component: "textarea" },
            },
            {
              type: "string",
              name: "schedule",
              label: "⏰ Horario disponible",
              description: "Ej: «Lunes de 17:00 a 20:00 (con cita previa)» o «Martes a domingo de 16:00 a 21:00».",
              required: true,
            },
            {
              type: "string",
              name: "feature",
              label: "Característica adicional o garantía",
              description: "Ej: «Privacidad y confidencialidad absoluta» o «Conexión segura desde donde estés».",
              required: true,
            },
            {
              type: "string",
              name: "featureIcon",
              label: "Icono de la característica",
              description: "Identificador de Lucide (ej: lucide:shield-check, lucide:video, lucide:lock).",
              required: true,
            },
            {
              type: "string",
              name: "primaryButtonText",
              label: "Texto del botón principal (Reservar)",
              description: "Ej: «Reservar presencial» o «Reservar online».",
              required: true,
            },
            {
              type: "string",
              name: "primaryButtonHref",
              label: "Enlace del botón principal",
              description: "Ruta de destino (ej: /reserva).",
              required: true,
            },
            {
              type: "string",
              name: "secondaryButtonText",
              label: "Texto del botón secundario (Más info)",
              description: "Ej: «Más información».",
              required: true,
            },
            {
              type: "string",
              name: "secondaryButtonHref",
              label: "Enlace del botón secundario",
              description: "Ruta de destino (ej: /terapia-presencial o /terapia-online).",
              required: true,
            },
          ],
        },
      ],
    },
    {
      type: "object",
      name: "specialtiesSection",
      label: "3. Sección de áreas y especialidades",
      fields: [
        {
          type: "string",
          name: "label",
          label: "Etiqueta superior",
          description: "Ej: «Áreas de acompañamiento».",
          required: true,
        },
        {
          type: "string",
          name: "title",
          label: "Título de la sección (H2)",
          description: "Ej: «¿En qué situaciones puedo acompañarte?».",
          required: true,
        },
        {
          type: "string",
          name: "description",
          label: "Descripción de apoyo",
          description: "Párrafo introductorio para las tarjetas de especialidad clínica.",
          required: true,
          ui: { component: "textarea" },
        },
        {
          type: "object",
          name: "items",
          label: "Tarjetas de especialidades clínicas",
          list: true,
          ui: {
            itemProps: (item) => ({
              label: item?.title || "Nueva especialidad",
            }),
          },
          fields: [
            {
              type: "string",
              name: "title",
              label: "Título de la especialidad",
              description: "Ej: «Duelo y pérdidas» o «Ansiedad y regulación emocional».",
              required: true,
            },
            {
              type: "string",
              name: "shortDescription",
              label: "Descripción breve",
              description: "Resumen breve para la tarjeta.",
              required: true,
              ui: { component: "textarea" },
            },
            {
              type: "string",
              name: "slug",
              label: "Identificador de enlace (Slug)",
              description: "Ruta de la página (ej: duelo, ansiedad, infanto-juvenil, adicciones).",
            },
            {
              type: "string",
              name: "icon",
              label: "Icono vectorial (opcional si hay miniatura)",
              description: "Identificador Lucide (ej: lucide:heart-crack, lucide:sparkles).",
            },
            {
              type: "image",
              name: "thumbnail",
              label: "Imagen en miniatura (opcional)",
              ui: imageFieldUi,
            },
            {
              type: "string",
              name: "thumbnailAlt",
              label: "Texto alternativo de la miniatura",
            },
          ],
        },
      ],
    },
    {
      type: "object",
      name: "cta",
      label: "4. Bloque final de llamada a la acción (Contacto)",
      fields: [
        {
          type: "string",
          name: "title",
          label: "Título destacado",
          required: true,
        },
        {
          type: "string",
          name: "description",
          label: "Texto de invitación",
          required: true,
          ui: { component: "textarea" },
        },
        ...ctaLinkFields,
      ],
    },
    {
      type: "string",
      name: "seoTitle",
      label: "4. Título SEO (Meta Title)",
      description: "Título para la pestaña del navegador y Google.",
      required: true,
    },
    {
      type: "string",
      name: "seoDescription",
      label: "5. Descripción SEO (Meta Description)",
      description: "Descripción breve para motores de búsqueda.",
      required: true,
      ui: { component: "textarea" },
    },
  ],
};
